version: '3.8'

services:
  dependencytrack:
    image: dependencytrack/bundled:latest
    container_name: dependencytrack
    ports:
      - "8585:8080" # Ajusta el puerto si es necesario
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/dependencytrack
      - DATABASE_USERNAME=dependencytrack
      - DATABASE_PASSWORD=dependencytrack
    volumes:
      - /home/romeo188/dependencytrack/xml_output:/data/xml_output
    networks:
      - red-tigo

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=dependencytrack
      - POSTGRES_PASSWORD=dependencytrack
      - POSTGRES_DB=dependencytrack
    ports:
      - "5432:5432" # Ajusta el puerto si es necesario
    networks:
      - red-tigo

  pandoc:
    image: pandoc/core:latest
    container_name: pandoc
    networks:
      - red-tigo
    volumes:
      - /home/romeo188/dependencytrack/xml_output:/workspace
    entrypoint: [ "sleep", "infinity" ]  # Mantiene el contenedor en ejecución para uso manual
    # Puedes ajustar el entrypoint o comando si tienes un script para convertir automáticamente el archivo XML a PDF

networks:
  red-tigo:
    driver: bridge
